name: RezzzFy Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        
      - name: Android kernel build
        # --- SARAN PERBAIKAN (BEST PRACTICE) ---
        # Mengganti '@master' dengan '@v1' agar build lebih stabil
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: RezzzFy
        with:
          arch: arm64
          compiler: gcc/12
          defconfig: ice-whyred-oldcam_defconfig
          image: Image.gz-dtb

      - name: Upload Built Kernel
        uses: actions/upload-artifact@v4
        with:
          name: built-kernel
          path: |
            # Path ini sudah benar, tidak perlu diubah.
            ${{ steps.build.outputs.outfile }}
